[package]
name = "maelstrom"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.7.5"
block-modes = "0.8.1"
rand_core = "0.6.3"
rand = "0.8.4"

# Client / Server communication
tokio = { version = "1.12.0", features = ["full"] }
futures = "0.3.21"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
rmp-serde = "1.0.0"
serde_bytes = "0.11.5"